# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: lint

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Install pnpm
    - run: npm install -g pnpm
    
    - name: Install dependencies
    - run: pnpm install --frozen-lockfile
    
    - name: Run "pnpm run lint"
    - run: pnpm run lint
